Bugfix/i os audio managment on app start
flutter-webrtc/flutter-webrtc pull request #1120
Opened 2022-10-12 10:23 UTC by PawelBijok

Fixes #1119

2022-10-12 10:38 UTC, dudeck approved these changes

2022-10-12 16:40 UTC, ycherniavskyi requested changes

2022-10-12 16:40 UTC, ycherniavskyi commented on common/darwin/Classes/FlutterWebRTCPlugin.m
> +                [[NSNotificationCenter defaultCenter] removeObserver:self];
Here is for sure some formatting issue. Please use the same formatting as in edited file.

2022-10-12 16:40 UTC, ycherniavskyi commented on common/darwin/Classes/FlutterWebRTCPlugin.m
> +    #endif
But what if several peer connection will be created simultaneously?

2022-10-12 16:40 UTC, ycherniavskyi commented on common/darwin/Classes/FlutterWebRTCPlugin.m
> -    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(didSessionRouteChange:) name:AVAudioSessionRouteChangeNotification object:session];
I think that at last this part must be left here, because technically we could want to get this notification event without active peer connection.

2022-10-17 04:28 UTC, cloudwebrtc commented
@PawelBijok hey, I added a judgment to the PR, it will only operate when RTCAudioSession.isActive, so the problem you described should be fixed, I opened the flutter-webrtc/example app when the zoom meeting was open, and the test results have been Will not affect the voip/music app anymore.
https://github.com/flutter-webrtc/flutter-webrtc/blob/main/common/darwin/Classes/FlutterWebRTCPlugin.m#L130

2025-04-29 01:28 UTC, closed without merging